import { Agent } from "@atproto/api";
import {
  JoseKey,
  Keyset,
  NodeOAuthClient,
  buildAtprotoLoopbackClientMetadata,
  requestLocalLock,
  type NodeSavedSession,
  type NodeSavedState,
  type OAuthClientMetadataInput,
} from "@atproto/oauth-client-node";
import { normalizeBaseUrl, siteUrl } from "@/lib/brand";
import {
  deleteBlueskyOauthSession,
  deleteBlueskyOauthState,
  getBlueskyOauthSession,
  getBlueskyOauthState,
  setBlueskyOauthSession,
  setBlueskyOauthState,
} from "@/lib/db";

export const BLUESKY_OAUTH_SCOPE = "atproto transition:generic";

export type BlueskyConnectionMetadata = {
  did: string;
  handle?: string;
};

type GlobalBluesky = {
  clientPromise?: Promise<NodeOAuthClient>;
};

function globalStore(): GlobalBluesky {
  const g = globalThis as typeof globalThis & { __kerygmaBlueskyOauth?: GlobalBluesky };
  if (!g.__kerygmaBlueskyOauth) g.__kerygmaBlueskyOauth = {};
  return g.__kerygmaBlueskyOauth;
}

function privateJwkRaw() {
  return process.env.BLUESKY_OAUTH_PRIVATE_JWK?.trim() || "";
}

function appOrigin() {
  return normalizeBaseUrl(process.env.NEXT_PUBLIC_APP_URL ?? siteUrl());
}

function isLocalOrigin(origin: string) {
  try {
    const url = new URL(origin);
    return (
      url.hostname === "localhost" ||
      url.hostname === "127.0.0.1" ||
      url.hostname === "[::1]"
    );
  } catch {
    return false;
  }
}

/** Bluesky loopback OAuth requires host 127.0.0.1 (not localhost). */
export function blueskyLoopbackOrigin() {
  const origin = appOrigin();
  try {
    const url = new URL(origin);
    const port = url.port || (url.protocol === "https:" ? "443" : "3000");
    if (port === "443" || port === "80") {
      return "http://127.0.0.1:3000";
    }
    return `http://127.0.0.1:${port}`;
  } catch {
    return "http://127.0.0.1:3000";
  }
}

export function isBlueskyLoopbackMode() {
  return isLocalOrigin(appOrigin());
}

/** Prefer confidential client when BLUESKY_OAUTH_PRIVATE_JWK is set. */
export function isBlueskyConfidentialClient() {
  return Boolean(privateJwkRaw()) && appOrigin().startsWith("https://");
}

/**
 * Live Bluesky OAuth is available for:
 * - local loopback (127.0.0.1 / localhost)
 * - production https apps (public client), or confidential when JWK is set
 */
export function isBlueskyConfigured() {
  if (isBlueskyLoopbackMode()) return true;
  return appOrigin().startsWith("https://");
}

export function blueskyRedirectUri() {
  if (isBlueskyLoopbackMode()) {
    return `${blueskyLoopbackOrigin()}/api/social/bluesky/callback`;
  }
  return `${appOrigin()}/api/social/bluesky/callback`;
}

export function blueskyClientMetadataUrl() {
  if (isBlueskyLoopbackMode()) {
    // Loopback client_id is generated by buildAtprotoLoopbackClientMetadata.
    return `${blueskyLoopbackOrigin()}/oauth-client-metadata.json`;
  }
  return `${appOrigin()}/oauth-client-metadata.json`;
}

function getClientMetadata(): OAuthClientMetadataInput {
  if (isBlueskyLoopbackMode()) {
    return buildAtprotoLoopbackClientMetadata({
      scope: BLUESKY_OAUTH_SCOPE,
      redirect_uris: [blueskyRedirectUri() as `http://127.0.0.1${string}`],
    });
  }

  const origin = appOrigin();
  const redirectUri = `${origin}/api/social/bluesky/callback` as const;

  if (isBlueskyConfidentialClient()) {
    return {
      client_id: `${origin}/oauth-client-metadata.json`,
      client_name: "Kerygma Social",
      client_uri: origin,
      logo_uri: `${origin}/opengraph-image`,
      tos_uri: `${origin}/terms`,
      policy_uri: `${origin}/privacy`,
      redirect_uris: [redirectUri],
      grant_types: ["authorization_code", "refresh_token"],
      response_types: ["code"],
      scope: BLUESKY_OAUTH_SCOPE,
      token_endpoint_auth_method: "private_key_jwt",
      token_endpoint_auth_signing_alg: "ES256",
      jwks_uri: `${origin}/.well-known/jwks.json`,
      dpop_bound_access_tokens: true,
      application_type: "web",
    };
  }

  // Public web client — works without BLUESKY_OAUTH_PRIVATE_JWK.
  return {
    client_id: `${origin}/oauth-client-metadata.json`,
    client_name: "Kerygma Social",
    client_uri: origin,
    logo_uri: `${origin}/opengraph-image`,
    tos_uri: `${origin}/terms`,
    policy_uri: `${origin}/privacy`,
    redirect_uris: [redirectUri],
    grant_types: ["authorization_code", "refresh_token"],
    response_types: ["code"],
    scope: BLUESKY_OAUTH_SCOPE,
    token_endpoint_auth_method: "none",
    dpop_bound_access_tokens: true,
    application_type: "web",
  };
}

async function getKeyset(): Promise<Keyset | undefined> {
  const raw = privateJwkRaw();
  if (!raw) return undefined;
  const jwk = JSON.parse(raw) as Record<string, unknown>;
  const key = await JoseKey.fromJWK(jwk);
  return new Keyset([key]);
}

export async function getBlueskyPublicJwks() {
  const keyset = await getKeyset();
  if (!keyset) return { keys: [] as unknown[] };
  return keyset.publicJwks;
}

function createStateStore() {
  return {
    async get(key: string): Promise<NodeSavedState | undefined> {
      const raw = await getBlueskyOauthState(key);
      if (!raw) return undefined;
      return JSON.parse(raw) as NodeSavedState;
    },
    async set(key: string, value: NodeSavedState): Promise<void> {
      await setBlueskyOauthState(key, JSON.stringify(value));
    },
    async del(key: string): Promise<void> {
      await deleteBlueskyOauthState(key);
    },
  };
}

function createSessionStore() {
  return {
    async get(key: string): Promise<NodeSavedSession | undefined> {
      const raw = await getBlueskyOauthSession(key);
      if (!raw) return undefined;
      return JSON.parse(raw) as NodeSavedSession;
    },
    async set(key: string, value: NodeSavedSession): Promise<void> {
      await setBlueskyOauthSession(key, JSON.stringify(value));
    },
    async del(key: string): Promise<void> {
      await deleteBlueskyOauthSession(key);
    },
  };
}

export async function getBlueskyOAuthClient(): Promise<NodeOAuthClient> {
  if (!isBlueskyConfigured()) {
    throw new Error("Bluesky OAuth is not configured");
  }

  const store = globalStore();
  if (!store.clientPromise) {
    store.clientPromise = (async () => {
      const keyset = await getKeyset();
      return new NodeOAuthClient({
        clientMetadata: getClientMetadata(),
        keyset,
        stateStore: createStateStore(),
        sessionStore: createSessionStore(),
        requestLock: requestLocalLock,
      });
    })().catch((error) => {
      store.clientPromise = undefined;
      throw error;
    });
  }

  return store.clientPromise;
}

export function encodeBlueskyOAuthState(userId: string, brandId: string) {
  return `${userId}:${brandId}`;
}

export function parseBlueskyOAuthState(state: string | null | undefined) {
  if (!state) return null;
  const separator = state.indexOf(":");
  if (separator <= 0 || separator === state.length - 1) return null;
  return {
    userId: state.slice(0, separator),
    brandId: state.slice(separator + 1),
  };
}

export function parseBlueskyMetadata(
  raw: string | null | undefined,
): BlueskyConnectionMetadata | null {
  if (!raw) return null;
  try {
    const parsed = JSON.parse(raw) as BlueskyConnectionMetadata;
    if (!parsed?.did || typeof parsed.did !== "string") return null;
    return parsed;
  } catch {
    return null;
  }
}

export function resolveBlueskyDid(
  connection: { accessToken?: string | null; metadata?: string | null },
): string | null {
  const fromMeta = parseBlueskyMetadata(connection.metadata)?.did;
  if (fromMeta) return fromMeta;
  const token = connection.accessToken?.trim();
  if (token?.startsWith("did:")) return token;
  return null;
}

export async function getBlueskyAgent(did: string) {
  const client = await getBlueskyOAuthClient();
  const session = await client.restore(did, "auto");
  return new Agent(session);
}

export async function verifyBlueskySession(did: string) {
  const agent = await getBlueskyAgent(did);
  const profile = await agent.getProfile({ actor: did });
  return {
    did,
    handle: profile.data.handle,
    displayName: profile.data.displayName ?? null,
  };
}

export async function revokeBlueskySession(did: string) {
  try {
    const client = await getBlueskyOAuthClient();
    await client.revoke(did);
  } catch {
    await deleteBlueskyOauthSession(did);
  }
}

async function uploadImageBlob(agent: Agent, imageUrl: string) {
  const response = await fetch(imageUrl);
  if (!response.ok) {
    throw new Error(`Could not download image for Bluesky (${response.status})`);
  }
  const contentType = response.headers.get("content-type") || "image/jpeg";
  if (!contentType.startsWith("image/")) {
    throw new Error("Bluesky image upload requires an image content type");
  }
  const bytes = new Uint8Array(await response.arrayBuffer());
  const uploaded = await agent.uploadBlob(bytes, { encoding: contentType });
  return uploaded.data.blob;
}

export async function publishToBluesky(input: {
  did: string;
  content: string;
  imageUrl?: string | null;
}) {
  const text = input.content.trim();
  if (!text) {
    throw new Error("Bluesky posts require text");
  }
  if (Array.from(text).length > 300) {
    throw new Error("Bluesky posts are limited to 300 characters");
  }

  const agent = await getBlueskyAgent(input.did);
  let embed: AppBskyEmbedImages | undefined;

  if (input.imageUrl) {
    const blob = await uploadImageBlob(agent, input.imageUrl);
    embed = {
      $type: "app.bsky.embed.images",
      images: [{ alt: "Post image", image: blob }],
    };
  }

  const result = await agent.post({
    text,
    createdAt: new Date().toISOString(),
    ...(embed ? { embed } : {}),
  });

  return result.uri;
}

type AppBskyEmbedImages = {
  $type: "app.bsky.embed.images";
  images: Array<{
    alt: string;
    image: Awaited<ReturnType<typeof uploadImageBlob>>;
  }>;
};

export function blueskyPostUrl(uri: string, handleOrDid?: string | null) {
  // at://did:plc:xxx/app.bsky.feed.post/rkey
  const match = uri.match(/^at:\/\/([^/]+)\/app\.bsky\.feed\.post\/([^/]+)$/);
  if (!match) return uri;
  const actor = handleOrDid?.replace(/^@/, "") || match[1];
  return `https://bsky.app/profile/${encodeURIComponent(actor!)}/post/${match[2]}`;
}
